language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SKELETON_VERSION="^3.4"
        - php: 7.1
          env: SKELETON_VERSION="^4.0"

before_install:
    - phpenv config-rm xdebug.ini || true
    - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
    - echo $CHANGED_FILES

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
    - cd flex
    - composer config extra.symfony.allow-contrib true
    - export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/${TRAVIS_PULL_REQUEST}

script:
    - composer req "helios-ag/fm-elfinder-bundle:^7.0"
    - printenv